#!/usr/bin/env bash
#Ping and address ip
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" >&2
    exit 1
else
	for (( i=1; i<=5; i++ )); do
    	ping -c  "$1"
done
fi
